baseURL = "http://example.com/"
languageCode = "en-us"
title = "Learner"
theme = "learner"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Creative Learner"
    description = "Distraction Free Theme for Learners."
    dateFormat = ""
[[menu.main]]
    name = "Courses"
    weight = 1
    hasChildren = true

    [[menu.main]]
        url = "/course/"
        name = "All courses"
        weight = 1
        parent = "Courses"

    [[menu.main]]
        url = "/categories/"
        name = "Course categories"
        weight = 2
        parent = "Courses"

[[menu.main]]
    url = "/blog/"
    name = "Blogs"
    weight = 2

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 5

[taxonomies]
  category = "categories"
  level = "levels"
  tag = "tags"

# Menu with social icons:
# The "name" field has to match the name of the icon to be used

[[menu.social]]
    url = "mailto:me@example.com"
    name = "envelope"
    weight = 1

[[menu.social]]
    url = "https://twitter.com/username/"
    name = "twitter"
    weight = 2

[[menu.social]]
    url = "https://www.facebook.com/username/"
    name = "facebook"
    weight = 3

[[menu.social]]
    url = "https://www.linkedin.com/in/username/"
    name = "linkedin"
    weight = 4

