baseURL = "http://example.com/"
languageCode = "en-us"
title = "Learner"
theme = "learner"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Creative Learner"
    description = "Distraction Free Theme for Learners."
    dateFormat = ""
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/poems/"
    name = "Poems"
    weight = 2

[[menu.main]]
    url = "/stories/"
    name = "Stories"
    weight = 3

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 4

[taxonomies]
  category = "categories"
  level = "levels"
  tag = "tags"

# Menu with social icons:
# The "name" field has to match the name of the icon to be used

[[menu.social]]
    url = "mailto:me@example.com"
    name = "envelope"
    weight = 1

[[menu.social]]
    url = "https://twitter.com/username/"
    name = "twitter"
    weight = 2

[[menu.social]]
    url = "https://www.facebook.com/username/"
    name = "facebook"
    weight = 3

[[menu.social]]
    url = "https://www.linkedin.com/in/username/"
    name = "linkedin"
    weight = 4

